% fusion_WriteCSV.m
% Version 6.3.4
% Step 2.5
% Write Output
%
% Project: New Fusion
% By xjtang
% Created On: 6/30/2017
% Last Update: 6/30/2017
%
% Input Arguments: 
%   main (Structure) - main inputs of the fusion process generated by fusion_inputs.m.
%
% Output Arguments: NA
%
% Instruction: 
%   1.Customize a config file for your project.
%   2.Run fusion_Inputs() first and get the returned structure of inputs
%   3.Run previous steps first to make sure required data are already generated.
%   4.Run this function with the stucture of inputs as the input argument.
%
% Version 1.0 - 6/30/2017
%   This script writes MODIS swath footpring as csv file
%
%----------------------------------------------------------------

function fusion_WriteCSV(main)

    % start timer
    tic;
    
    % set file path
    FileName.MOD09SUB = main.output.modsubf;
    
    % loop through all existing MOD09SUB files
    for I_Day = 1:numel(main.date.swath)
        
        % construct date string
        Day = main.date.swath(I_Day);
        DayStr = num2str(Day);
        
        % find files
        File.MOD09SUB = dir([FileName.MOD09SUB,'M*D','09FUS','*',DayStr,'*']);
        if numel(File.MOD09SUB) < 1
            disp(['Cannot find MOD09FUS for Julian Day: ', DayStr]);
            continue;
        end
        
        for I_TIME = 1:numel(File.MOD09SUB)
            
            % construct time string
            TimeStr = regexp(File.MOD09SUB(I_TIME).name,'\.','split');
            TimeStr = char(TimeStr(4));

            % check current platform
            fileName = char(File.MOD09SUB(I_TIME).name);
            thisPlat = fileName(regexp(fileName,'M.?D'):(regexp(fileName,'M.?D')+2));
            
            % check if results for this file already exist
            output = dir([main.output.csv thisPlat '*' DayStr '*' TimeStr '*']);
            if numel(output)>=1
                disp([DayStr ' result already exist, skip this file.']);
                continue;
            end
                        
            % load MOD09SUB
            MOD09SUB = load([FileName.MOD09SUB,File.MOD09SUB(I_TIME).name]);

            % get data for csv
            csv = swath2csv(MOD09SUB,250);

            % write csv
            csvwrite([main.output.csv,thisPlat,'09CSV.','250m.',DayStr,'.',TimeStr,'.csv'],csv)
            
        end

        disp(['Done with ',DayStr,' in ',num2str(toc,'%.f'),' seconds']);
    end

    % done
    
end
