% fusion_WriteHDF.m
% Version 6.3.4
% Step 4
% Write Output
%
% Project: New Fusion
% By xjtang
% Created On: Unknown
% Last Update: 2/4/2016
%
% Input Arguments: 
%   main (Structure) - main inputs of the fusion process generated by fusion_inputs.m.
%
% Output Arguments: NA
%
% Instruction: 
%   1.Customize a config file for your project.
%   2.Run fusion_Inputs() first and get the returned structure of inputs
%   3.Run previous steps first to make sure required data are already generated.
%   4.Run this function with the stucture of inputs as the input argument.
%
% Version 6.0 - Unknown (by Q. Xin)
%   This script generage MODIS swath data based on Landsat synthetic data
%       with BRDF correction.
%
% Updates of Version 6.1 - 10/7/2014 
%   1.Updated comments.
%   2.Changed coding style.
%   3.Modified for work flow of fusion version 6.1.
%   4.Changed from script to function
%   5.Modified the code to incorporate the use of fusion_inputs structure.
%
% Updates of Version 6.2 - 11/24/2014 
%   1.Bug fixed.
%   2.Updated comments.
%   3.Added support for 250m fusion.
%   4.Added support for BRDF correstion.
%   5.Added support for Aqua
%
% Updates of Version 6.2.1 - 1/21/2015 
%   1.Fixed a bug in brdf support.
%
% Updates of Version 6.3 - 4/6/2015 
%   1.Combined 250 and 500 fusion.
%   2.Bug fixed.
%
% Updates of Version 6.3.1 - 7/1/2015
%   1.Changed output file name style.
%
% Updates of Version 6.3.2 - 10/18/2015
%   1.Implement model constants.
%
% Updates of Version 6.3.3 - 12/12/2015
%   1.Added support for combining terra and aqua.
%   2.Optimized performance.
%   3.Process both terra and aqua by default.
%
% Updates of Version 6.3.4 - 2/4/2016
%   1.Removed brdf correction part.
%   2.Replaced system command with matlab command.
%
% Released on Github on 10/15/2014, check Github Commits for updates afterwards.
%----------------------------------------------------------------

function fusion_WriteHDF(main)

    % start timer
    tic;
    
    % set file path
    FileName.MOD09SUB = main.output.modsubf;
    FileName.MOD09SUBB = main.output.modsubbrdf;
    
    % loop through all existing MOD09SUB files
    for I_Day = 1:numel(main.date.swath)
        
        % construct date string
        Day = main.date.swath(I_Day);
        DayStr = num2str(Day);
        
        % find files
        File.MOD09SUB = dir([FileName.MOD09SUB,'M*D','09FUS','*',DayStr,'*']);
        if numel(File.MOD09SUB) < 1
            disp(['Cannot find MOD09FUS for Julian Day: ', DayStr]);
            continue;
        end
        
        for I_TIME = 1:numel(File.MOD09SUB)
            
            % construct time string
            TimeStr = regexp(File.MOD09SUB(I_TIME).name,'\.','split');
            TimeStr = char(TimeStr(4));

            % check current platform
            fileName = char(File.MOD09SUB(I_TIME).name);
            thisPlat = fileName(regexp(fileName,'M.?D'):(regexp(fileName,'M.?D')+2));
            
            % check if results for this file already exist
            output = dir([main.output.fusion thisPlat '*' DayStr '*' TimeStr '*']);
            if numel(output)>=1
                disp([DayStr ' result already exist, skip this file.']);
                continue;
            end
            
            % copy original swath data to output location 
            copyfile([main.input.swath thisPlat '*' DayStr '*' TimeStr '*'],main.output.fusion);
            
            % load MOD09SUB and MOD09SUBBRDF
            MOD09SUB = load([FileName.MOD09SUB,File.MOD09SUB(I_TIME).name]);
            
            % Find HDF file to write
            HDFFile = dir([main.output.fusion,thisPlat,'*',DayStr,'*',TimeStr,'*']);
            if numel(HDFFile) ~= 1
                disp(['Cannot find HDFFile for Julian Day: ', DayStr]);
                continue;
            end

            % Transform
            Dims250 = size(hdfread([main.output.fusion,HDFFile.name],['250','m Surface Reflectance Band 1']));
            Dims500 = size(hdfread([main.output.fusion,HDFFile.name],['500','m Surface Reflectance Band 1']));

            FUS09RED250 = ones(Dims250)*(main.cons.outna);
            FUS09RED250(MOD09SUB.MODLine250,MOD09SUB.MODSamp250) = MOD09SUB.FUS09RED250;        
            FUS09RED250 = int16(FUS09RED250);

            FUS09NIR250 = ones(Dims250)*(main.cons.outna);
            FUS09NIR250(MOD09SUB.MODLine250,MOD09SUB.MODSamp250) = MOD09SUB.FUS09NIR250;        
            FUS09NIR250 = int16(FUS09NIR250);
            
            FUS09RED500 = ones(Dims500)*(main.cons.outna);
            FUS09RED500(MOD09SUB.MODLine500,MOD09SUB.MODSamp500) = MOD09SUB.FUS09RED500;        
            FUS09RED500 = int16(FUS09RED500);

            FUS09NIR500 = ones(Dims500)*(main.cons.outna);
            FUS09NIR500(MOD09SUB.MODLine500,MOD09SUB.MODSamp500) = MOD09SUB.FUS09NIR500;        
            FUS09NIR500 = int16(FUS09NIR500);

            FUS09BLU500 = ones(Dims500)*(main.cons.outna);
            FUS09BLU500(MOD09SUB.MODLine500,MOD09SUB.MODSamp500) = MOD09SUB.FUS09BLU500;        
            FUS09BLU500 = int16(FUS09BLU500);

            FUS09GRE500 = ones(Dims500)*(main.cons.outna);
            FUS09GRE500(MOD09SUB.MODLine500,MOD09SUB.MODSamp500) = MOD09SUB.FUS09GRE500;        
            FUS09GRE500 = int16(FUS09GRE500);

            FUS09SWIR500 = ones(Dims500)*(main.cons.outna);
            FUS09SWIR500(MOD09SUB.MODLine500,MOD09SUB.MODSamp500) = MOD09SUB.FUS09SWIR500;        
            FUS09SWIR500 = int16(FUS09SWIR500);

            FUS09SWIR2500 = ones(Dims500)*(main.cons.outna);
            FUS09SWIR2500(MOD09SUB.MODLine500,MOD09SUB.MODSamp500) = MOD09SUB.FUS09SWIR2500;        
            FUS09SWIR2500 = int16(FUS09SWIR2500);

            % write HDF file
            [~] = writeHDF([main.output.fusion,HDFFile.name],11,FUS09BLU500);
            [~] = writeHDF([main.output.fusion,HDFFile.name],12,FUS09GRE500);
            [~] = writeHDF([main.output.fusion,HDFFile.name],9,FUS09RED500);
            [~] = writeHDF([main.output.fusion,HDFFile.name],10,FUS09NIR500);
            [~] = writeHDF([main.output.fusion,HDFFile.name],14,FUS09SWIR500);
            [~] = writeHDF([main.output.fusion,HDFFile.name],15,FUS09SWIR2500);
            [~] = writeHDF([main.output.fusion,HDFFile.name],7,FUS09RED250);
            [~] = writeHDF([main.output.fusion,HDFFile.name],8,FUS09NIR250);
            
        end

        disp(['Done with ',DayStr,' in ',num2str(toc,'%.f'),' seconds']);
    end

    % done
    
end
