% fusion_Fusion.m
% Version 6.3.1
% Step 3
% Main Fusion Process
%
% Project: New Fusion
% By xjtang
% Created On: Unknown
% Last Update: 7/1/2015
%
% Input Arguments: 
%   main (Structure) - main inputs of the fusion process generated by fusion_inputs.m.
%
% Output Arguments: NA
%
% Instruction: 
%   1.Customize a config file for your project.
%   2.Run fusion_Inputs() first and get the returned structure of inputs
%   3.Run previous steps first to make sure required data are already generated.
%   4.Run this function with the stucture of inputs as the input argument.
%
% Version 6.0 - Unknown (by Q. Xin)
%   This script creates MODIS swath data based on Landsat synthetic data.
%   This script saves the results as Matlab object called MOD09SUB that contains the data and related metadata.
%
% Updates of Version 6.1 - 10/1/2014 
%   1.Updated comments.
%   2.Changed coding style.
%   3.Modified for work flow of fusion version 6.1.
%   4.Changed from script to function
%   5.Modified the code to incorporate the use of fusion_inputs structure.
%   6.Modified the code to process all Landsat bands
%   7.The code now save output to MOD09SUBF instead of overwriting old files.
%
% Updates of Version 6.1.1 - 10/15/2014 
%   1.The script now checks for existing results and skip.
%
% Updates of Version 6.2 - 11/24/2014 
%   1.Bugs Fixed.
%   2.Added support of 250m fusion.
%   3.Updated comments.
%   4.Added support for Aqua.
%
% Updates of Version 6.2.1 - 12/18/2014 
%   1.Set ETM value to nan if it is 0
%
% Updates of Version 6.3 - 4/4/2015 
%   1.Combined 250 and 500 fusion.
%   2.Bug fixed
%
% Updates of Version 6.3.1 - 7/1/2015
%   1.Changed output file name style.
%
% Released on Github on 10/15/2014, check Github Commits for updates afterwards.
%----------------------------------------------------------------

function fusion_Fusion(main)

    % calculate pixel center coordinates
    [Samp,Line] = meshgrid(main.etm.sample,main.etm.line);
    ETMGeo.Northing = main.etm.ulNorth-Line*30+15;
    ETMGeo.Easting = main.etm.ulEast +Samp*30-15;
    [ETMGeo.Lat,ETMGeo.Lon] = utm2deg(ETMGeo.Easting,ETMGeo.Northing,main.etm.utm);
    ETMGeo.Line = main.etm.line;
    ETMGeo.Samp = main.etm.sample;

    % start timer
    tic;
    
    % check platform
    plat = main.set.plat;
    
    % loop through all etm images
    for I_Day=1:numel(main.date.swath)
        
        % get date information of all images
        Day = main.date.swath(I_Day);
        DayStr = num2str(Day);

        % check if result already exist
        File.Check = dir([main.output.modsubf plat '*' 'ALL' '*' DayStr '*']);
        if numel(File.Check) >= 1
            disp([DayStr ' already exist, skip this date.']);
            continue;
        end
        
        % read ETM
        File.ETM = dir([main.input.etm,'*',DayStr,'*.hdr']);
        if  numel(File.ETM) ~= 1
            disp(['Cannot find ETM for Julian Day: ', DayStr]);     
            continue;
        end

        ETM = multibandread([main.input.etm,File.ETM.name(1:(length(File.ETM.name)-4))],...
            [numel(main.etm.line),numel(main.etm.sample),main.etm.band],'int16',0,main.etm.interleave,'ieee-le');
        ETM(ETM==0) = nan;
        ETM(ETM>10000) = 10000;
        % ETM(ETM<0) = 0;

        ETMBLU = ETM(:,:,1);
        ETMGRE = ETM(:,:,2);
        ETMRED = ETM(:,:,3);
        ETMNIR = ETM(:,:,4);
        ETMSWIR = ETM(:,:,5);
        ETMSWIR2 = ETM(:,:,6);

        % find MOD09SUB files
        File.MOD09SUB = dir([main.output.modsub,plat,'09SUB.','ALL','*',DayStr,'*']);

        if numel(File.MOD09SUB)<1
            disp(['Cannot find MOD09SUB for Julian Day: ', DayStr]);
            continue;
        end

        % loop through MOD09SUB file of current date
        for I_TIME = 1:numel(File.MOD09SUB)
            TimeStr = regexp(File.MOD09SUB(I_TIME).name,'\.','split');
            TimeStr = char(TimeStr(4));

            % load MOD09SUB
            MOD09SUB = load([main.output.modsub,File.MOD09SUB(I_TIME).name]);

            % fusion
            MOD09SUB.FUS09RED250 = etm2swath(ETMRED,MOD09SUB,ETMGeo,250);
            MOD09SUB.FUS09NIR250 = etm2swath(ETMNIR,MOD09SUB,ETMGeo,250);
            MOD09SUB.FUS09RED500 = etm2swath(ETMRED,MOD09SUB,ETMGeo,500);
            MOD09SUB.FUS09NIR500 = etm2swath(ETMNIR,MOD09SUB,ETMGeo,500);
            MOD09SUB.FUS09BLU500 = etm2swath(ETMBLU,MOD09SUB,ETMGeo,500);
            MOD09SUB.FUS09GRE500 = etm2swath(ETMGRE,MOD09SUB,ETMGeo,500);
            MOD09SUB.FUS09SWIR500 = etm2swath(ETMSWIR,MOD09SUB,ETMGeo,500);
            MOD09SUB.FUS09SWIR2500 = etm2swath(ETMSWIR2,MOD09SUB,ETMGeo,500);

            % save
            save([main.output.modsubf,plat,'09FUS.','ALL.',DayStr,'.',TimeStr,'.mat'],'-struct','MOD09SUB');
            disp(['Done with ',DayStr,' in ',num2str(toc,'%.f'),' seconds']);
        end
    end

    % done
    
end
