% fusion_GenMap.m
% Version 1.2.1
% Step 9
% Generate Map

% Project: New Fusion
% By xjtang
% Created On: 7/7/2014
% Last Update: 2/6/2016
%
% Input Arguments: 
%   main (Structure) - main inputs of the fusion process generated by fusion_inputs.m.
%   
% Output Arguments: NA
%
% Instruction: 
%   1.Customize a config file for your project.
%   2.Run fusion_Inputs() first and get the returned structure of inputs
%   3.Run previous steps first to make sure required data are already generated.
%   4.Run this function with the stucture of inputs as the input argument.
%
% Version 1.0 - 7/7/2015
%   This script generates change map in envi format based on fusion result.
%
% Updates of Version 1.0.1 - 7/13/2015
%   1.Added a new type of map.
%
% Updates of Version 1.0.2 - 7/18/2015
%   1.Added support for new model parameter.
%
% Updates of Version 1.0.3 - 8/18/2015
%   1.Fixed a bug that may cause the script to delete other files.
%
% Updates of Version 1.0.4 - 9/17/2015
%   1.Generaes all maps as a package now.
%   2.Added a check to see if the previous process is completed.
%
% Updates of Version 1.1 - 9/25/2015
%   1.Generates coefficients maps.
%
% Updates of Version 1.1.1 - 10/18/2015
%   1.Pass class codes to core funcion.
%   2.Adjusted according to change in change detection.
%   3.Implement model constants.
%
% Updates of Version 1.1.2 - 11/15/2015
%   1.Adjusted the COEF map output according to change in main model.
%
% Updates of Version 1.2 - 1/28/2016
%   1.Assign class process is moved to fusion_change.m.
%   2.This script assembles the maps only.
%
% Updates of Version 1.2.1 - 2/6/2016
%   1.Export single class maps for all three major classes.
%   2.Replaced system command with matlab command.
%   3.Consolidate single class maps into one file.
%
% Created on Github on 7/7/2015, check Github Commits for updates afterwards.
%----------------------------------------------------------------

function fusion_GenMap(main)
    
    % initialize
    MAP = ones(length(main.etm.line),length(main.etm.sample),3)*main.cons.outna;
    SCMAP = zeros(length(main.etm.line),length(main.etm.sample),3);
    CMAP = ones(length(main.etm.line),length(main.etm.sample),6,3,length(main.model.band)+1)*main.cons.outna;
    CMapName = {'DateOfChange';'DateOfDetection';'ClassMap';'SingleClassMap'};
    CoefName1 = {'Mean';'Std';'Intercept';'Slope';'Rsquared';'RMSE'};
    CoefName2 = {'Pre';'Post';'All'};
    
    % start timer
    tic;
    
    % check if line catch is completed
    Complete.Check = dir([main.output.chgmat 'ts.r*.chg.mat']);
    if numel(Complete.Check)/length(main.etm.line) <= 0.7
        disp('Line cache are not complete, abort.');
        return;  
    end
    
    % line by line processing
    for i = (main.etm.line)'
        
        % check if result exist
        File.Check = dir([main.output.chgmat 'ts.r' num2str(i) '.chg.mat']);
        if numel(File.Check) == 0
            disp([num2str(i) ' line cache does not exist, skip this line.']);
            continue;  
        end
        
        % read input data
        CHG = load([main.output.chgmat 'ts.r' num2str(i) '.chg.mat']);
        
        % assign change map result
        MAP(i,:,1) = CHG.ChangeDate;
        MAP(i,:,2) = CHG.DetectDate;
        MAP(i,:,3) = CHG.Class;
        
        % assign sinle class maps
        SCMAP(i,((CHG.Class==main.LCclass.Change)|(CHG.Class==main.LCclass.CEdge)...
            |(CHG.Class==main.LCclass.Prob)),1) = 1;
        SCMAP(i,((CHG.Class==main.LCclass.NonForest)|(CHG.Class==main.LCclass.NFEdge)),2) = 1;
        SCMAP(i,(CHG.Class==main.LCclass.Forest),3) = 1;
        SCMAP(i,(CHG.Class==main.LCclass.NA),:) = -9999;

        % assign coef map result
        CMAP(i,:,:,:,:,1) = CHG.Coef(:,[1:2,4:7],:,:);
        
        % show progress
        disp(['Done with line ',num2str(i),' in ',num2str(toc,'%.f'),' seconds']);
        
    end
    
    % export change maps
    for i = 1:length(CMapName)
        
        % determine file name
        outFile = [main.output.chgmap char(CMapName(i))];

        % see if change map already exist
        if exist(outFile,'file')
            disp('Change map already exist, overwrite.')
            delete(outFile);
            delete([outFile,'.hdr']);
        end
        
        if i == length(CMapName)
            % export change map
            enviwrite(outFile,SCMAP,[main.etm.ulEast,main.etm.ulNorth],main.etm.utm,3,[30,30],'bsq');
        else
            % export change map
            enviwrite(outFile,squeeze(MAP(:,:,i)),[main.etm.ulEast,main.etm.ulNorth],main.etm.utm,3,[30,30],'bsq');
        end
        
    end

    % export coef maps
    for i = 1:length(CoefName1)
        for j = 1:length(CoefName2)
            
            % determine file name
            outFile = [main.output.coefmap char(CoefName1(i)) char(CoefName2(j))];

            % see if change map already exist
            if exist(outFile,'file')
                disp('Coef map already exist, overwrite.')
                delete(outFile);
                delete([outFile,'.hdr']);
            end

            % export change map
            enviwrite(outFile,squeeze(CMAP(:,:,i,j,:)),[main.etm.ulEast,main.etm.ulNorth],main.etm.utm,3,[30,30],'bsq');

        end
    end
    
    % done
    
end

